export enum AuthErrors {
  EMAIL_ALREADY_TAKEN = 'USER_ALREADY_EXISTS',
  USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST',
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  USERNAME_ALREADY_TAKEN = 'USERNAME_ALREADY_TAKEN',
}
