export enum ListErrors {
  WRONG_LIST_ID = 'WRONG_LIST_ID',
  NOT_ALLOWED = 'NOT_ALLOWED',
  FAV_LIST_OWNED_BY_USER = 'FAV_LIST_OWNED_BY_USER',
  FAV_LIST_ALREADY_EXISTS = 'FAV_LIST_ALREADY_EXISTS',
}
