FROM node:18 as builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn

COPY . .

RUN npm run build:prod

# Nginx image
FROM nginx:1.23.4

# Копируем статические файлы приложения из предыдущего этапа
COPY --from=builder ./dist /usr/share/nginx/html

# Копируем конфигурацию nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Указываем порт, на котором будет работать nginx
EXPOSE 80

# Команда для запуска nginx при запуске контейнера
CMD ["nginx", "-g", "daemon off;"]
