version: "3.8"

services:
  postgres-db:
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DATABASE}"
    ports:
      - 5432:5432

  redis-db:
    image: redis:latest
    restart: no
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWOR: "${REDIS_PASSWORD}"
      REDIS_USER: "${REDIS_USER}"
      REDIS_PORT: "${REDIS_PORT}"

  adminer:
    image: adminer
    depends_on:
      - postgres-db
    restart: no
    ports:
      - 5050:8080

volumes:
  postgres-db:
    driver: local
  redis-db:
    driver: local
