version: '3.8'

services:
  postgres-db:
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DATABASE}"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    depends_on:
      - postgres-db
    restart: no
    ports:
      - 5050:8080

volumes:
  postgres-db:
    driver: local