version: '3.8'

services:
  ######################### Nginx proxy #########################
  nginx-proxy:
    build: 
      context: ./nginx-proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/nginx/certs

    networks:
      - moofy-network
      - moofy-test-network

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: unless-stopped
    volumes_from:
      - "nginx-proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy

  ######################## Frontend #########################
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=moofy.ru
      - LETSENCRYPT_HOST=moofy.ru
    networks:
      - moofy-network

  ######################### Backend #########################

  backend-prod:
    image: moofy-backend
    restart: unless-stopped
    container_name: backend-prod
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
    depends_on:
      - redis-db
    networks:
      - moofy-network

  nginx-backend:
    build:
      context: ./nginx-backend/prod
      dockerfile: Dockerfile
    container_name: nginx-backend
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=api.moofy.ru
      - VIRTUAL_PORT=4444
      - LETSENCRYPT_HOST=api.moofy.ru
    depends_on:
      - backend-prod
    networks:
      - moofy-network

  ######################### For backend #########################

  redis-db:
    image: redis:7.0.5-alpine
    restart: unless-stopped
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis-db:/data
    networks:
      - moofy-network

volumes:
  redis-db:
    driver: local
  test-redis-db:
    driver: local

networks:
  moofy-network:
    driver: bridge
  moofy-test-network:
    driver: bridge
