version: '3.8'

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres-db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PG_ADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PG_ADMIN_PASSWORD}"
    ports:
      - 5050:80

  redis-db:
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - '6379:6379'
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis-db:/data
    
volumes:
  redis-db:
    driver: local
