version: '3.8'

services:
  ######################### Proxy #########################
  root-proxy:
    build: 
      context: ./nginx-proxy
      dockerfile: Dockerfile
    container_name: root-proxy
    restart: unless-stopped
    ports:
      - "3000:80"
      - "3001:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/nginx/certs
    networks:
      - moofy-network

  ######################### SSL #########################
  ssl-companion:
    image: nginxproxy/acme-companion
    container_name: ssl-companion
    restart: unless-stopped
    volumes_from:
      - "root-proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=root-proxy
    depends_on:
      - root-proxy

    ######################## Site #########################
  site:
    image: moofy-site
    build:
      context: ../
      dockerfile: deploy/Dockerfile
      target: site
    container_name: site
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=v2.moofy.ru
      - LETSENCRYPT_HOST=v2.moofy.ru
      - VIRTUAL_PORT=3000
    networks:
      - moofy-network

  ######################### Api #########################

  api:
    image: moofy-api
    restart: unless-stopped
    container_name: api
    build:
      context: ../
      dockerfile: deploy/Dockerfile
      target: api
    environment:
      - VIRTUAL_HOST=api.v2.moofy.ru
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=api.v2.moofy.ru
    networks:
      - moofy-network
    depends_on:
      migrations:
        condition: service_completed_successfully

  migrations:
    image: amacneil/dbmate
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ../db:/db
    command: -d /db/migrations up
    networks:
      - moofy-network

networks:
  moofy-network:
    driver: bridge
