name: One-time script

on:
  workflow_dispatch:
    inputs:
      script:
        type: string
        required: true
        description: "Script name. For example: 123-do-something"

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install

      - run: pnpm run:one-time ${{ github.event.inputs.script }}
