name: One-time script

on:
  workflow_dispatch:
    inputs:
      script:
        type: string
        required: true
        description: "Script name. For example: 123-do-something"
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install

      - name: Setup .env file
        run: |
          touch .env

          echo ENV=staging >> .env

          echo COOKIE_SECRET=${{ secrets.COOKIE_SECRET }} >> .env

          echo UNOFFICIAL_KP_API_KEYS=${{ secrets.UNOFFICIAL_KP_API_KEYS }} >> .env

          echo PG_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo PG_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo PG_HOST=${{ secrets.POSTGRES_HOST }} >> .env
          echo PG_PORT=${{ secrets.POSTGRES_PORT }} >> .env
          echo PG_DATABASE=${{ secrets.POSTGRES_DB_NAME }} >> .env
          echo DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:${{ secrets.POSTGRES_PORT }}/${{ secrets.POSTGRES_DB_NAME }} >> .env

          echo S3_ACCESS_KEY_ID="${{ secrets.S3_KEY_ID }}" >> .env
          echo S3_SECRET_ACCESS_KEY="${{ secrets.S3_KEY_SECRET }}" >> .env
          echo S3_BUCKET_NAME="${{ secrets.S3_BUCKET_NAME }}" >> .env

          echo LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }} >> .env

      - name: Run script
        run: pnpm run:one-time ${{ github.event.inputs.script }}
