name: moofy-frontend
run-name: Deploy
on: 
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn build:prod

      - name: Build project
        run: yarn build

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ secrets.FRONTEND_DESTINATION }}
          remote_host: ${{ secrets.VPS_IP }}
          remote_user: ${{ secrets.VPS_USERNAME }}
          remote_key: ${{ secrets.VPS_SSH_KEY }}

